function runGUI()

    [nutrient_names, food_names, food_nutrients] = loadDatabase();

    window = figure...
    (...
        'Visible', 'off',...
        'Name', 'Food Finder',...
        'MenuBar', 'none',...
        'DockControls', 'off',...
        'Position', [500, 250, 1000, 500]...
    );
    
    temporary = {};
    food_stuffs = {};
    iterator = 1;
    for i = food_names
        temporary{numel(temporary) + 1} = i{1};
        temporary{numel(temporary) + 1} = true;
        for j = food_nutrients(iterator,:)
            temporary{numel(temporary) + 1} = j(1);
        end
        food_stuffs = [food_stuffs; temporary];

        temporary = {};
        iterator = iterator + 1;
    end
    
    columnname = {'Food', 'Include'};
    
    for i = nutrient_names
        columnname{numel(columnname) + 1} = i{1};
    end
    
    columnformat = {'numeric', 'logical', 'bank'};
    food_stuffs_table = uitable...
    (...
            'Data', food_stuffs,... 
            'ColumnName', columnname,...
            'ColumnFormat', columnformat,...
            'ColumnEditable', [false true false],...
            'ColumnWidth', {60 60 120 'auto'},...
            'RowName', [],...
            'Position', [20 80 500 400]...
    );

    desired_nutrients = ...
    {...
        'Energy'            10000000    'Joule';...
        'Carbohydrate'      0.4         'kg';...
        'Fat'               0.3         'kg';...
        'Protein'           0.2         'kg';...
        'Fiber'             0.1         'kg';...
        'Cholesterol'       3*10^-4     'kg';...
    };
        
    desired = uitable...
    (...
            'Data', desired_nutrients,... 
            'ColumnName', {'Resource', 'Amount', 'Unit'},...
            'ColumnFormat', {'numeric', 'numeric', 'bank'},...
            'ColumnEditable', [false true false],...
            'ColumnWidth', {100 80 120 'auto'},...
            'RowName', [],...
            'Position', [540 80 200 400]...
    );
        
    output_table = {};
	result = uitable...
    (...
            'Data', output_table,... 
            'ColumnName', {'Food', 'Amount', 'Unit'},...
            'ColumnFormat', {'numeric', 'numeric', 'bank'},...
            'ColumnEditable', [false false false],...
            'ColumnWidth', {120 100 120 'auto'},...
            'RowName', [],...
            'Position', [760 80 220 400]...
    );
        
    btn = uicontrol...
    (...
        'Style', 'pushbutton', 'String', 'Clear',...
        'Position', [20 20 70 20],...
        'Callback', @close...
    );       

    compute_button = uicontrol...
    (...
        'Style', 'pushbutton', 'String', 'Compute',...
        'Position', [20 40 70 20],...
        'Callback', @compute...
    );
    
    reload_button = uicontrol...
    (...
        'Style', 'pushbutton', 'String', 'Reload',...
        'Position', [20 60 70 20],...
        'Callback', @reloadDatabase...
    );
    
    function close(source, callbackdata)
        window.Visible = 'off';
        close(window);
    end

    function setOutputTable(food_amount_array, deviation)
        output_table = food_amount_array;
        result.Data = output_table;
    end

    function compute(source, callbackdata)
        columm_count = numel(food_stuffs(1, :));
        input_nutrients = cell2mat(food_stuffs(:, 3:columm_count));
        cell2mat(desired_nutrients(:,2));
        [ food_amount_array, deviation ] = computeOptimalFood( transpose(input_nutrients), cell2mat(desired_nutrients(:,2)) );
        setOutputTable(food_amount_array, deviation);
    end

    function reloadDatabase(source, callbackdata)
        [nutrient_names, food_names, food_nutrients] = loadDatabase();
    end

    window.Visible = 'on';
end

